version: 3

tasks:
  build:
    desc: Build Java image
    cmd: |
      docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag java:21-graalvm \
            --file java/Dockerfile \
            .
    silent: true

  push:
    desc: Push java image to docker hub
    cmds:
      - docker tag java:21-graalvm dksifoua/java:21-graalvm
      - docker push dksifoua/java:21-graalvm

  scan:
    desc: Scan built image for vulnerabilities
    cmd: trivy image java:21-graalvm

  verify:
    desc: Check docker image best practices has been followed
    cmd: dockle --exit-code 1 --exit-level info java:21-graalvm
    silent: true
