version: 3

env:
  DOCKER_BUILDKIT: 1
  DOCKER_DEFAULT_PLATFORM: linux/amd64,linux/arm64

tasks:
  build:
    desc: Build Java image
    cmd: |
      docker buildx build \
        --tag dksifoua/java:21-graalvm \
        --file java/21.Dockerfile \
        . {{ .CLI_ARGS }}
    silent: true

  push:
    desc: Push java image to docker hub
    cmd: docker push dksifoua/java:21-graalvm

  scan:
    desc: Scan built image for vulnerabilities
    cmd: trivy image dksifoua/java:21-graalvm

  verify:
    desc: Check docker image best practices has been followed
    cmd: dockle --exit-code 1 --exit-level info dksifoua/java:21-graalvm
    silent: true
